repos:
  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort
      language: system
      require_serial: true
      types_or: [cython, pyi, python]
      args: ['--filter-files']

    - id: black
      name: black
      entry: black
      language: system
      require_serial: true
      types_or: [python, pyi]
